blog/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import path, include
from blog import views
from .feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path("", views.blog_view, name="index"),
    path("category/<str:category_name>", views.blog_view, name="category_blog_view"),
    path("tag/<str:tag_name>", views.blog_view, name="tag_blog_view"),
    path("rss/feed/", LatestEntriesFeed(), name="LatestEntriesFeed"),
    path("author/<str:author_name>", views.blog_view, name="author_blog_view"),
    path("search/", views.blog_search, name="blog_search"),
    path("<int:pid>", views.single_blog, name="single_blog"),
    path("comment", views.post_comment, name="post_comment"),
    path("single", views.blog_single, name="single"),
    path("test_view", views.test_view, name="test_view"),
    path("test_simple", views.test_simple, name="test_simple"),
    path("<str:name>", views.name_tester, name="name_tester"),
    path("<str:name>/<str:family>", views.name_family_tester, name="name_family_tester"),
    path("<str:name>/<str:family>/<int:age>", views.name_family_age_tester, name="name_family_age_tester"),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website import views
from website.sitemaps import WebsiteStaticViewSitemap

sitemaps = {
    'websitestatic': WebsiteStaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("http-test/", views.http_test, name="http-test"),
    # path("json-test/", views.json_test, name="json-test"),
    path("", include("website.urls"), name="website"),
    # path("website/", include("website.urls"), name="website"),
    path("blog/", include("blog.urls"), name="blog"),
    # path("accounts/", include("accounts.urls"), name="accounts"),
    path("accounts/", include("django.contrib.auth.urls"), name="accounts"),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", include("robots.urls"), name="robots"),
    path("__debug__/", include("debug_toolbar.urls")),
]

# static ('static, 'base / static')
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
import django.contrib.auth.urls

from website import views
app_name = 'website'
urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.index, name="home"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("newsletter", views.newsletter, name="newsletter"),
    path("test_view", views.test_view, name="test_view"),
    path("test", views.test, name="test"),
]

website/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.


class Contact(models.Model):
    name = models.CharField(
        max_length=255,
    )
    subject = models.CharField(
        max_length=255,
    )
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name+': '+self.email


class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

website/forms.py
from django import forms
from website.models import Contact, Newsletter
from captcha.fields import CaptchaField

class NameForm(forms.Form):
    name = forms.CharField(max_length=255)
    subject = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        # fields = ("name", "subject", "email", "message")
        fields = "__all__"


class NewsletterForm(forms.ModelForm):

    class Meta:
        model = Newsletter
        # fields = ("name", "subject", "email", "message")
        fields = "__all__"

website/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib import messages
from website.forms import NameForm, ContactForm, NewsletterForm


def index(request):
    # return HttpResponse('<h1>This is Home<h1>')
    return render(request, 'website/index.html')


def home(request):
    return index()


def about(request):
    # return HttpResponse('<h1>This is about<h1>')
    return render(request, 'website/about.html')


def contact(request):
    # return HttpResponse('<h1>This is contact<h1>')
    if request.method == 'POST':
        # print('Post request')
        # name = request.POST.get('name')
        # subject = request.POST.get('subject')
        # email = request.POST.get('email')
        # message = request.POST.get('message')
        # print(f'name: {name}, subject: {subject}, email: {email}, message: {message}')
        # c = Contact()
        # c.name = name
        # c.subject = subject
        # c.email = email
        # c.message = message
        # c.save()
        # print(name)
        # form = NameForm(request.POST)
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            form.save()
            # messages.add_message(request, messages.SUCCESS, 'Your Message has been sent successfully!')
            messages.success(
                request, 'Your Message has been sent successfully!')
            # return HttpResponse(f"Thanks for {name}, {subject}, {email} and {message}")
        else:
            # messages.add_message(request, messages.ERROR, 'Your Message has not been sent successfully!')
            messages.warning(
                request, 'Your Message has not been sent successfully!')
    else:
        form = ContactForm()
    context = {
        'form': form
    }
    return render(request, 'website/contact.html', context)


def newsletter(request):
    # return HttpResponse('<h1>This is contact<h1>')
    if request.method == 'POST':
        # print('Post request')
        # name = request.POST.get('name')
        # subject = request.POST.get('subject')
        # email = request.POST.get('email')
        # message = request.POST.get('message')
        # print(f'name: {name}, subject: {subject}, email: {email}, message: {message}')
        # c = Contact()
        # c.name = name
        # c.subject = subject
        # c.email = email
        # c.message = message
        # c.save()
        # print(name)
        # form = NameForm(request.POST)
        form = NewsletterForm(request.POST)
        if form.is_valid():
            # name = form.cleaned_data['name']
            # subject = form.cleaned_data['subject']
            # email = form.cleaned_data['email']
            # message = form.cleaned_data['message']
            form.save()
            # return HttpResponse(f"Thanks for {name}, {subject}, {email} and {message}")
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')
    # return render(request, 'website/contact.html', context)


def test_view(request):
    context = {'name': 'Gamba Ozaka'}
    return render(request, 'website/test_view.html', context)


def test(request):
    if request.method == 'POST':
        # print('Post request')
        # name = request.POST.get('name')
        # subject = request.POST.get('subject')
        # email = request.POST.get('email')
        # message = request.POST.get('message')
        # print(f'name: {name}, subject: {subject}, email: {email}, message: {message}')
        # c = Contact()
        # c.name = name
        # c.subject = subject
        # c.email = email
        # c.message = message
        # c.save()
        # print(name)
        # form = NameForm(request.POST)
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            form.save()
            return HttpResponse(f"Thanks for {name}, {subject}, {email} and {message}")
    else:
        form = ContactForm()
    context = {
        'name': 'Gamba Ozaka',
        'form': form
    }
    return render(request, 'website/test.html', context)

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- start banner Area -->
  <section class="about-banner relative">
    <div class="overlay overlay-bg"></div>
    <div class="container">
      <div class="row d-flex align-items-center justify-content-center">
        <div class="about-content col-lg-12">
          <h1 class="text-white">About Us</h1>
          <p class="text-white link-nav">
            <a href="{% url 'website:index' %}">Home</a> <span class="lnr lnr-arrow-right"></span> <a href="{% url 'website:about' %}">About Us</a>
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- End banner Area -->

  <!-- Start about-info Area -->
  <section class="about-info-area section-gap">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 info-left">
          <img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="" />
        </div>
        <div class="col-lg-6 info-right">
          <h6>About Us</h6>
          <h1>Who We Are?</h1>
          <p>Here, I focus on a range of items and features that we use in life without giving them a second thought. such as Coca Cola. Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
        </div>
      </div>
    </div>
  </section>
  <!-- End about-info Area -->

  <!-- Start price Area -->
  <section class="price-area section-gap">
    <div class="container">
      <div class="row d-flex justify-content-center">
        <div class="menu-content pb-70 col-lg-8">
          <div class="title text-center">
            <h1 class="mb-10">We Provide Affordable Prices</h1>
            <p>Well educated, intellectual people, especially scientists at all times demonstrate considerably.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <div class="single-price">
            <h4>Cheap Packages</h4>
            <ul class="price-list">
              <li class="d-flex justify-content-between align-items-center">
                <span>New York</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Maldives</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Sri Lanka</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Nepal</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Thiland</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Singapore</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="single-price">
            <h4>Luxury Packages</h4>
            <ul class="price-list">
              <li class="d-flex justify-content-between align-items-center">
                <span>New York</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Maldives</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Sri Lanka</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Nepal</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Thiland</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Singapore</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="single-price">
            <h4>Camping Packages</h4>
            <ul class="price-list">
              <li class="d-flex justify-content-between align-items-center">
                <span>New York</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Maldives</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Sri Lanka</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Nepal</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Thiland</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
              <li class="d-flex justify-content-between align-items-center">
                <span>Singapore</span>
                <a href="#" class="price-btn">$1500</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End price Area -->

  <!-- Start other-issue Area -->
  <section class="other-issue-area section-gap">
    <div class="container">
      <div class="row d-flex justify-content-center">
        <div class="menu-content pb-70 col-lg-9">
          <div class="title text-center">
            <h1 class="mb-10">Other issues we can help you with</h1>
            <p>We all live in an age that belongs to the young at heart. Life that is.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3 col-md-6">
          <div class="single-other-issue">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="" />
            </div>
            <a href="#"><h4>Rent a Car</h4></a>
            <p>The preservation of human life is the ultimate value, a pillar of ethics and the foundation.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="single-other-issue">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="" />
            </div>
            <a href="#"><h4>Cruise Booking</h4></a>
            <p>I was always somebody who felt quite sorry for myself, what I had not got compared.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="single-other-issue">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="" />
            </div>
            <a href="#"><h4>To Do List</h4></a>
            <p>The following article covers a topic that has recently moved to center stage–at least it seems.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="single-other-issue">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="" />
            </div>
            <a href="#"><h4>Food Features</h4></a>
            <p>There are many kinds of narratives and organizing principles. Science is driven by evidence.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End other-issue Area -->

  <!-- Start testimonial Area -->
  <section class="testimonial-area section-gap">
    <div class="container">
      <div class="row d-flex justify-content-center">
        <div class="menu-content pb-70 col-lg-8">
          <div class="title text-center">
            <h1 class="mb-10">Testimonial from our Clients</h1>
            <p>The French Revolution constituted for the conscience of the dominant aristocratic class a fall from</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="active-testimonial">
          <div class="single-testimonial item d-flex flex-row">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/elements/user1.png' %}" alt="" />
            </div>
            <div class="desc">
              <p>Do you want to be even more successful? Learn to love learning and growth. The more effort you put into improving your skills, the bigger the payoff you.</p>
              <h4>Harriet Maxwell</h4>
              <div class="star">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
              </div>
            </div>
          </div>
          <div class="single-testimonial item d-flex flex-row">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/elements/user2.png' %}" alt="" />
            </div>
            <div class="desc">
              <p>A purpose is the eternal condition for success. Every former smoker can tell you just how hard it is to stop smoking cigarettes. However.</p>
              <h4>Carolyn Craig</h4>
              <div class="star">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
              </div>
            </div>
          </div>
          <div class="single-testimonial item d-flex flex-row">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/elements/user1.png' %}" alt="" />
            </div>
            <div class="desc">
              <p>Do you want to be even more successful? Learn to love learning and growth. The more effort you put into improving your skills, the bigger the payoff you.</p>
              <h4>Harriet Maxwell</h4>
              <div class="star">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
              </div>
            </div>
          </div>
          <div class="single-testimonial item d-flex flex-row">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/elements/user2.png' %}" alt="" />
            </div>
            <div class="desc">
              <p>A purpose is the eternal condition for success. Every former smoker can tell you just how hard it is to stop smoking cigarettes. However.</p>
              <h4>Carolyn Craig</h4>
              <div class="star">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
              </div>
            </div>
          </div>
          <div class="single-testimonial item d-flex flex-row">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/elements/user1.png' %}" alt="" />
            </div>
            <div class="desc">
              <p>Do you want to be even more successful? Learn to love learning and growth. The more effort you put into improving your skills, the bigger the payoff you.</p>
              <h4>Harriet Maxwell</h4>
              <div class="star">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
              </div>
            </div>
          </div>
          <div class="single-testimonial item d-flex flex-row">
            <div class="thumb">
              <img class="img-fluid" src="{% static 'img/elements/user2.png' %}" alt="" />
            </div>
            <div class="desc">
              <p>A purpose is the eternal condition for success. Every former smoker can tell you just how hard it is to stop smoking cigarettes. However.</p>
              <h4>Carolyn Craig</h4>
              <div class="star">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End testimonial Area -->
{% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- start banner Area -->
  <section class="relative about-banner">
    <div class="overlay overlay-bg"></div>
    <div class="container">
      <div class="row d-flex align-items-center justify-content-center">
        <div class="about-content col-lg-12">
          <h1 class="text-white">Contact Us</h1>
          <p class="text-white link-nav">
            <a href="{% url 'website:index' %}">Home</a> <span class="lnr lnr-arrow-right"></span> <a href="{% url 'website:contact' %}">Contact Us</a>
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- End banner Area -->
  <!-- Start contact-page Area -->
  <section class="contact-page-area section-gap">
    <div class="container">
      <div class="row">
        {% comment %} <div class="map-wrap" style="width:100%; height: 445px;" id="map"></div> {% endcomment %}
        <div class="col-lg-4 d-flex flex-column address-wrap">
          <div class="single-contact-address d-flex flex-row">
            <div class="icon">
              <span class="lnr lnr-home"></span>
            </div>
            <div class="contact-details">
              <h5>Binghamton, New York</h5>
              <p>4343 Hinkle Deegan Lake Road</p>
            </div>
          </div>
          <div class="single-contact-address d-flex flex-row">
            <div class="icon">
              <span class="lnr lnr-phone-handset"></span>
            </div>
            <div class="contact-details">
              <h5>00 (958) 9865 562</h5>
              <p>Mon to Fri 9am to 6 pm</p>
            </div>
          </div>
          <div class="single-contact-address d-flex flex-row">
            <div class="icon">
              <span class="lnr lnr-envelope"></span>
            </div>
            <div class="contact-details">
              <h5>support@colorlib.com</h5>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
        {% include 'widgets\contact-form-widget.html' %}
      </div>
    </div>
  </section>
  <!-- End contact-page Area -->
{% endblock %}

templates/website/test.html
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test_simple</title>
</head>
<body>
    <h1>test_simple Header</h1>
    <p>test: {% hello %} </p>
    <p>test: {% plustwo 2 %} </p>
    <p>test: {% plustwo %} </p>
    <p>test: {% totalposts %} </p>
    <p>test: {% posts %} </p>

    <form action="{% url 'website:test' %}" method="post">
        {% csrf_token %}
        {% comment %} <label for="name">Name:</label>
        <input name="name" type="text"> {% endcomment %}
        {% comment %} <label for="subject">Subject:</label>
        <input name="subject" type="text">
        <label for="email">Email:</label>
        <input name="email" type="email">
        <label for="message">Message:</label>
        <input name="message" type="text"> {% endcomment %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    {% comment %} {% for post in posts%}
    <p>title: {{ post.title }}</p>
    <p>snippet: {{ post.content|snippetarg:10 }} </p>
    {% endfor %} {% endcomment %}

    {% comment %} {% popularposts 4 %} {% endcomment %}
</body>
</html>

templates/website/test_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test_view</title>
</head>
<body>
    {% if name %}
    <h1>{{name}}</h1>
    {%else%}
    <h1>test_view</h1>
    {%endif%}
</body>
</html>