blog/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import path, include
from blog import views
from .feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path("", views.blog_view, name="index"),
    path("category/<str:category_name>", views.blog_view, name="category_blog_view"),
    path("tag/<str:tag_name>", views.blog_view, name="tag_blog_view"),
    path("rss/feed/", LatestEntriesFeed(), name="LatestEntriesFeed"),
    path("author/<str:author_name>", views.blog_view, name="author_blog_view"),
    path("search/", views.blog_search, name="blog_search"),
    path("<int:pid>", views.single_blog, name="single_blog"),
    path("comment", views.post_comment, name="post_comment"),
    path("single", views.blog_single, name="single"),
    path("test_view", views.test_view, name="test_view"),
    path("test_simple", views.test_simple, name="test_simple"),
    path("<str:name>", views.name_tester, name="name_tester"),
    path("<str:name>/<str:family>", views.name_family_tester, name="name_family_tester"),
    path("<str:name>/<str:family>/<int:age>", views.name_family_age_tester, name="name_family_age_tester"),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website import views
from website.sitemaps import WebsiteStaticViewSitemap

sitemaps = {
    'websitestatic': WebsiteStaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("http-test/", views.http_test, name="http-test"),
    # path("json-test/", views.json_test, name="json-test"),
    path("", include("website.urls"), name="website"),
    # path("website/", include("website.urls"), name="website"),
    path("blog/", include("blog.urls"), name="blog"),
    # path("accounts/", include("accounts.urls"), name="accounts"),
    path("accounts/", include("django.contrib.auth.urls"), name="accounts"),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", include("robots.urls"), name="robots"),
    path("__debug__/", include("debug_toolbar.urls")),
]

# static ('static, 'base / static')
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
import django.contrib.auth.urls

from website import views
app_name = 'website'
urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.index, name="home"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("newsletter", views.newsletter, name="newsletter"),
    path("test_view", views.test_view, name="test_view"),
    path("test", views.test, name="test"),
]

blog/models.py
from django.urls import reverse
from django.utils.timezone import now
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.


class Category(models.Model):
    name = models.CharField(
        max_length=255,
    )

    def __str__(self):
        return self.name
    verbose_name = 'Category'
    verbose_name = 'Categories'


class Tag(models.Model):
    name = models.CharField(
        max_length=255,
    )

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(
        max_length=255,
    )
    content = models.TextField()
    # tag
    # category
    counted_view = models.IntegerField(
        default=0,
    )
    status = models.BooleanField(
        default=False,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    published_at = models.DateTimeField(
        null=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )
    login_require = models.BooleanField(
        default=False,
    )
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)

    # tag = models. ManyToManyField(Tag)
    tags = TaggableManager()

    class Meta:
        ordering = ['-created_at', 'status']
        # verbose_name = 'پست'
        # verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title

    def snippets(self):
        return self.content[:100] + '...'

    def get_absolute_url(self):
        # this or def location(self, item): in sitemap
        return reverse('blog:single_blog', kwargs={'pid': self.id})


class Comment(models.Model):
    name = models.CharField(
        max_length=255,
        default="User",
    )
    email = models.EmailField()
    subject = models.CharField(
        max_length=255,
    )
    message = models.TextField()
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )
    approved = models.BooleanField(
        default=False,
    )
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.subject

templates/widgets/author-widget.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
  <img src="{% static 'img/blog/user-info.png' %}" alt="" />
  {% if author %}
    <a href="{% url 'blog:author_blog_view' author.username %}"><h4>{{ author }}</h4></a>
    <p>{{ author.get_full_name }}</p>
  {% else %}
    <a href="#"><h4>Charlie Barber</h4></a>
  {% endif %}
  <ul class="social-links">
    <li>
      <a href="#"><i class="fa fa-facebook"></i></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-twitter"></i></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-github"></i></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-behance"></i></a>
    </li>
  </ul>
  <p>Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.</p>
</div>

templates/widgets/comment-post-widget.html
{% load static %}
<div class="comment-form">
  <h4>Leave a Comment</h4>
  <form action="{% url 'blog:single_blog' post.id %}" method="post">
    {% csrf_token %}
    {% comment %} {{ form }} {% endcomment %}
    <input type="hidden" id="id_post" name="post" value="{{post.id}}" />
    <div class="form-group form-inline">
      <div class="form-group col-lg-6 col-md-12 name">
        <input type="text" class="form-control" name="name" id="name" {% if user %}disabled placeholder="{{user.username}}"{% else %}placeholder="Enter Name"{% endif %} onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'" />
      </div>
      <div class="form-group col-lg-6 col-md-12 email">
        <input type="email" class="form-control" name="email" id="email" {% if user %}disabled placeholder="{{user.email}}" {% else %} placeholder="Enter Email" {% endif %} onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" />
      </div>
    </div>
    <div class="form-group">
      <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'" />
    </div>
    <div class="form-group">
      <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
    </div>
    <button class="genric-btn primary text-uppercase" type="submit">Send Message</button>
    {% comment %} <a href="#" class="primary-btn text-uppercase">Post Comment</a> {% endcomment %}
    <div class="col-lg-6">
      {% if form.errors %}
      <div class="alert alert-error">
          <h4>Please fix the following error</h4>
          <ul>
              {% for field in form %}
                  {% if field.errors %}
                      {% for error in field.errors %}
                      <li>
                          <a href="#id_{{field.name}}" class="error">{{ error|escape }}</a>
                      </li>
                      {% endfor %}
                  {% endif %}
              {% endfor %}
          </ul>
      </div>
      <ul class="messages">
          {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}											
  </div>
  <div class="col-lg-6">
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}											
  </div>
  </form>
</div>

templates/widgets/comment-widget.html
{% load static %}
{% load blog_tags %}
{% load humanize %}
<div class="comments-area">
  {% comment %} <h4>05 Comments</h4> {% endcomment %}
  <h4>{{ comments.count }} Comment{% if comments.count > 1 %}s{% endif %}</h4>
  {% comment %} <h4>{{ comments|length }} Comment{% if comments.count > 1 %}s{% endif %}</h4> {% endcomment %}
  {% comment %} <h4>{% comments_count post.id %} Comment {% if comments_count post.id > 1 %}s{% endif %}</h4> {% endcomment %}
  {% comment %} {% if comments %} {% endcomment %}
    {% for comment in comments %}
      <div class="comment-list">
        <div class="single-comment justify-content-between d-flex">
          <div class="user justify-content-between d-flex">
            <div class="thumb">
              <img src="{% static 'img/blog/c1.jpg' %}" alt="" />
            </div>
            <div class="desc">
              <h5><a href="#">{{ comment.author }}</a></h5>
              <p class="date">{{ comment.created_at|naturalday }}</p>
              <h6>{{ comment.subject }}</h6>
              <p class="comment">{{ comment.message }}</p>
            </div>
          </div>
          <div class="reply-btn">
            <a href="" class="btn-reply text-uppercase">reply</a>
          </div>
        </div>
      </div>
      {% empty %}
      <p>No Comments Yet!</p>
    {% endfor %}
  {% comment %} {% else %} {% endcomment %}
    {% comment %} <div class="comment-list">
      <div class="single-comment justify-content-between d-flex">
        <div class="user justify-content-between d-flex">
          <div class="thumb">
            <img src="{% static 'img/blog/c1.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <h5><a href="#">Emilly Blunt</a></h5>
            <p class="date">December 4, 2017 at 3:12 pm</p>
            <p class="comment">Never say goodbye till the end comes!</p>
          </div>
        </div>
        <div class="reply-btn">
          <a href="" class="btn-reply text-uppercase">reply</a>
        </div>
      </div>
    </div>
    <div class="comment-list left-padding">
      <div class="single-comment justify-content-between d-flex">
        <div class="user justify-content-between d-flex">
          <div class="thumb">
            <img src="{% static 'img/blog/c2.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <h5><a href="#">Elsie Cunningham</a></h5>
            <p class="date">December 4, 2017 at 3:12 pm</p>
            <p class="comment">Never say goodbye till the end comes!</p>
          </div>
        </div>
        <div class="reply-btn">
          <a href="" class="btn-reply text-uppercase">reply</a>
        </div>
      </div>
    </div>
    <div class="comment-list left-padding">
      <div class="single-comment justify-content-between d-flex">
        <div class="user justify-content-between d-flex">
          <div class="thumb">
            <img src="{% static 'img/blog/c3.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <h5><a href="#">Annie Stephens</a></h5>
            <p class="date">December 4, 2017 at 3:12 pm</p>
            <p class="comment">Never say goodbye till the end comes!</p>
          </div>
        </div>
        <div class="reply-btn">
          <a href="" class="btn-reply text-uppercase">reply</a>
        </div>
      </div>
    </div>
    <div class="comment-list">
      <div class="single-comment justify-content-between d-flex">
        <div class="user justify-content-between d-flex">
          <div class="thumb">
            <img src="{% static 'img/blog/c4.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <h5><a href="#">Maria Luna</a></h5>
            <p class="date">December 4, 2017 at 3:12 pm</p>
            <p class="comment">Never say goodbye till the end comes!</p>
          </div>
        </div>
        <div class="reply-btn">
          <a href="" class="btn-reply text-uppercase">reply</a>
        </div>
      </div>
    </div>
    <div class="comment-list">
      <div class="single-comment justify-content-between d-flex">
        <div class="user justify-content-between d-flex">
          <div class="thumb">
            <img src="{% static 'img/blog/c5.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <h5><a href="#">Ina Hayes</a></h5>
            <p class="date">December 4, 2017 at 3:12 pm</p>
            <p class="comment">Never say goodbye till the end comes!</p>
          </div>
        </div>
        <div class="reply-btn">
          <a href="" class="btn-reply text-uppercase">reply</a>
        </div>
      </div>
    </div> {% endcomment %}
  {% comment %} {% endif %} {% endcomment %}
</div>

templates/widgets/contact-form-widget.html
{% load static %}
<div class="col-lg-8">
    <form class="form-area contact-form text-right" id="myForm" action="{% url 'website:contact' %}" method="post">
        <div class="row">	
            {% csrf_token %}
            <div class="col-lg-6 form-group">
                <input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control" required="" type="text">
            
                <input name="email" placeholder="Enter email address" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control" required="" type="email">

                <input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control" required="" type="text">
            </div>
            <div class="col-lg-6 form-group">
                <textarea class="common-textarea form-control" name="message" placeholder="Enter Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'" required=""></textarea>				
            </div>
            {% comment %} <div class="col-lg-12">
                <div class="alert-msg" style="text-align: left;"></div>
                <button class="genric-btn primary" style="float: right;" type="submit">Send Message</button>											
            </div> {% endcomment %}
            <div class="col-lg-6">
                {% if form.errors %}
                <div class="alert alert-error">
                    <h4>Please fix the following error</h4>
                    <ul>
                        {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                <li>
                                    <a href="#id_{{field.name}}" class="error">{{ error|escape }}</a>
                                </li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}											
            </div>
            <div class="col-lg-6">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}											
            </div>
            <div class="col-lg-12">
                <div class="pb-3">
                    {{form.captcha}}
                </div>
                <div class="alert-msg" style="text-align: left;"></div>
                <button class="genric-btn primary" style="float: right;" type="submit">Send Message</button>
            </div>
        </div>
        {% comment %} <div class="row">
            {% if messages %}
            <div class="col-lg-6 form-group">
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div> {% endcomment %}
    </form>	
</div>

templates/widgets/disqus-comment-widget.html
<div id="disqus_thread"></div>
<script>
  /**
   *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
   *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
  /*
        var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        */
  ;(function () {
    // DON'T EDIT BELOW THIS LINE
    var d = document,
      s = d.createElement('script')
    s.src = 'https://127-0-0-1-8000-ka9not76b1.disqus.com/embed.js'
    s.setAttribute('data-timestamp', +new Date())
    ;(d.head || d.body).appendChild(s)
  })()
</script>
<noscript>
  Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>

templates/widgets/navigation-area-widget.html
{% load static %}
<div class="navigation-area">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
      <div class="thumb">
        <a href="#"><img class="img-fluid" src="{% static 'img/blog/prev.jpg' %}" alt="" /></a>
      </div>
      <div class="arrow">
        <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
      </div>
      <div class="detials">
        <p>Prev Post</p>
        <a href="#"><h4>Space The Final Frontier</h4></a>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
      <div class="detials">
        <p>Next Post</p>
        <a href="#"><h4>Telescopes 101</h4></a>
      </div>
      <div class="arrow">
        <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
      </div>
      <div class="thumb">
        <a href="#"><img class="img-fluid" src="{% static 'img/blog/next.jpg' %}" alt="" /></a>
      </div>
    </div>
  </div>
</div>

templates/widgets/popular-post-widget.html
{% load humanize %}
{% load static %}
{% load blog_tags %}
<div class="single-sidebar-widget popular-post-widget">
  <h4 class="popular-title">Popular Posts</h4>
  <div class="popular-post-list">
    {% if posts %}
      {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
          <div class="thumb">
            <img class="img-fluid" src="{{ post.image.url }}" alt="" />
          </div>
          <div class="details">
            <a href="{% url 'blog:single_blog' pid=post.id %}"><h6>{{ post.title }}</h6></a>
            {% comment %} <p>{{ post.published_at|date:"d M Y"}}</p> {% endcomment %}
            <p>{{ post.published_at|naturaltime}}</p>
            {% comment %} <p>{{post.id|apnumber}}</p> {% endcomment %}
          </div>
        </div>
      {% endfor %}
    {% else %}
      <div class="single-post-list d-flex flex-row align-items-center">
        <div class="thumb">
          <img class="img-fluid" src="{% static 'img/blog/pp1.jpg' %}" alt="" />
        </div>
        <div class="details">
          <a href="blog-single.html"><h6>Space The Final Frontier</h6></a>
          <p>02 Hours ago</p>
        </div>
      </div>
      <div class="single-post-list d-flex flex-row align-items-center">
        <div class="thumb">
          <img class="img-fluid" src="{% static 'img/blog/pp2.jpg' %}" alt="" />
        </div>
        <div class="details">
          <a href="blog-single.html"><h6>The Amazing Hubble</h6></a>
          <p>02 Hours ago</p>
        </div>
      </div>
      <div class="single-post-list d-flex flex-row align-items-center">
        <div class="thumb">
          <img class="img-fluid" src="{% static 'img/blog/pp3.jpg' %}" alt="" />
        </div>
        <div class="details">
          <a href="blog-single.html"><h6>Astronomy Or Astrology</h6></a>
          <p>02 Hours ago</p>
        </div>
      </div>
    {% endif %}
  </div>
</div>

templates/widgets/post-category-widget.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
  <h4 class="category-title">Post Catgories</h4>
  <ul class="cat-list">
    {% for name,value in categories_count.items %}
      <li>
        <a href="{% url 'blog:category_blog_view' name %}" class="d-flex justify-content-between">
          <p>{{ name }}</p>
          <p>{{ value }}</p>
        </a>
      </li>
    {% endfor %}
  </ul>
</div>

templates/widgets/tag-cloud-widget.html
{% load static %}
<div class="single-sidebar-widget tag-cloud-widget">
  <h4 class="tagcloud-title">Tag Clouds</h4>
  <ul>
    {% comment %} {% for tag in post.tags.all %}
    <li>
      <a href="">{{ tag }}</a>
    </li>
    {% endfor %} {% endcomment %}
    {% comment %} {% post.tags.all %} {% endcomment %}
    {% comment %} {% for name,value in tags_count.items %}
      <li>
        <a href="{% url 'blog:tag_blog_view' name %}">{{ name }} - {{ value }} - {{value}}</a>
      </li>
    {% endfor %} {% endcomment %}
    {% for name,value,if_tag in tags_count %}
      <li>
        {% if if_tag %}
        <h3>
          <a href="{% url 'blog:tag_blog_view' name %}">{{ name }} ({{value}})</a>
        </h3>
        {% else %}
        <a href="{% url 'blog:tag_blog_view' name %}">{{ name }} ({{value}})</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>

templates/widgets/top-category-widget.html
{% load static %}
<section class="top-category-widget-area pt-90 pb-90">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="" />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Social life</h4>
                <span></span>
                <p>Enjoy your social life together</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}" alt="" />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Politics</h4>
                <span></span>
                <p>Be a part of politics</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}" alt="" />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Food</h4>
                <span></span>
                <p>Let the food be finished</p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>