blog/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import path, include
from blog import views
from .feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path("", views.blog_view, name="index"),
    path("category/<str:category_name>", views.blog_view, name="category_blog_view"),
    path("tag/<str:tag_name>", views.blog_view, name="tag_blog_view"),
    path("rss/feed/", LatestEntriesFeed(), name="LatestEntriesFeed"),
    path("author/<str:author_name>", views.blog_view, name="author_blog_view"),
    path("search/", views.blog_search, name="blog_search"),
    path("<int:pid>", views.single_blog, name="single_blog"),
    path("comment", views.post_comment, name="post_comment"),
    path("single", views.blog_single, name="single"),
    path("test_view", views.test_view, name="test_view"),
    path("test_simple", views.test_simple, name="test_simple"),
    path("<str:name>", views.name_tester, name="name_tester"),
    path("<str:name>/<str:family>", views.name_family_tester, name="name_family_tester"),
    path("<str:name>/<str:family>/<int:age>", views.name_family_age_tester, name="name_family_age_tester"),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website import views
from website.sitemaps import WebsiteStaticViewSitemap

sitemaps = {
    'websitestatic': WebsiteStaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("http-test/", views.http_test, name="http-test"),
    # path("json-test/", views.json_test, name="json-test"),
    path("", include("website.urls"), name="website"),
    # path("website/", include("website.urls"), name="website"),
    path("blog/", include("blog.urls"), name="blog"),
    # path("accounts/", include("accounts.urls"), name="accounts"),
    path("accounts/", include("django.contrib.auth.urls"), name="accounts"),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", include("robots.urls"), name="robots"),
    path("__debug__/", include("debug_toolbar.urls")),
]

# static ('static, 'base / static')
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
import django.contrib.auth.urls

from website import views
app_name = 'website'
urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.index, name="home"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("newsletter", views.newsletter, name="newsletter"),
    path("test_view", views.test_view, name="test_view"),
    path("test", views.test, name="test"),
]

blog/models.py
from django.urls import reverse
from django.utils.timezone import now
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.


class Category(models.Model):
    name = models.CharField(
        max_length=255,
    )

    def __str__(self):
        return self.name
    verbose_name = 'Category'
    verbose_name = 'Categories'


class Tag(models.Model):
    name = models.CharField(
        max_length=255,
    )

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(
        max_length=255,
    )
    content = models.TextField()
    # tag
    # category
    counted_view = models.IntegerField(
        default=0,
    )
    status = models.BooleanField(
        default=False,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    published_at = models.DateTimeField(
        null=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )
    login_require = models.BooleanField(
        default=False,
    )
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)

    # tag = models. ManyToManyField(Tag)
    tags = TaggableManager()

    class Meta:
        ordering = ['-created_at', 'status']
        # verbose_name = 'پست'
        # verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title

    def snippets(self):
        return self.content[:100] + '...'

    def get_absolute_url(self):
        # this or def location(self, item): in sitemap
        return reverse('blog:single_blog', kwargs={'pid': self.id})


class Comment(models.Model):
    name = models.CharField(
        max_length=255,
        default="User",
    )
    email = models.EmailField()
    subject = models.CharField(
        max_length=255,
    )
    message = models.TextField()
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )
    approved = models.BooleanField(
        default=False,
    )
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.subject

blog/forms.py
from django import forms
from captcha.fields import CaptchaField

from .models import Comment


class CommentForm(forms.ModelForm):
    # captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ("post", "name", "subject", "email", "message")
        # fields = "__all__"

blog/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .forms import CommentForm
from .models import Post, Tag, Category, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

# def blog_view(request, category_name=None, tag_name=None, author_name=None):


def blog_view(request, **kwargs):
    # posts = get_list_or_404(Post, status=True)
    posts = Post.objects.filter(status=True)
    if kwargs.get('category_name'):
        posts = posts.filter(category__name=kwargs['category_name'])
    if kwargs.get('tag_name'):
        posts = posts.filter(tags__name=kwargs['tag_name'])
        print(posts.count())
        # my_posts = posts.filter(tags__name=kwargs['tag_name'])
        # posts = posts.filter(tags__name__in=kwargs['tag_name'])
        # print(kwargs['tag_name'])
        # print(posts.count())
        # print(my_posts.count())
    if kwargs.get('author_name'):
        posts = posts.filter(author__username=kwargs['author_name'])
    paginator = Paginator(posts, 3)
    try:
        page_number = request.GET.get('page')
        posts = paginator.get_page(page_number)
    except PageNotAnInteger:
        posts = paginator.get_page(1)
    except EmptyPage:
        posts = paginator.get_page(paginator.num_pages)
    categories = Category.objects.all()
    # tags = Tags.objects.all()
    context = {
        # 'tags': tags,
        'categories': categories,
        'posts': posts,
    }
    if request.user.is_authenticated:
        # context += {
        #     'user': request.user
        # }
        context['user'] = request.user
    return render(request, 'blog/blog-home.html', context)

# def category_blog_view(request, category_name):
#     # posts = get_list_or_404(Post, category=category_name, status=True)
#     posts = Post.objects.filter(status=True)
#     posts = posts.filter(category__name=category_name)
#     categories = Category.objects.all()
#     tags = Tag.objects.all()
#     context = {
#         'posts': posts,
#         'tags': tags,
#         'categories': categories,
#     }
#     return render(request, 'blog/blog-home.html', context)

# def tag_blog_view(request, tag_name):
#     # posts = get_list_or_404(Post, category=category_name, status=True)
#     posts = Post.objects.filter(status=True)
#     posts = posts.filter(tag__name=tag_name)
#     categories = Category.objects.all()
#     tags = Tag.objects.all()
#     context = {
#         'posts': posts,
#         'tags': tags,
#         'categories': categories,
#     }
#     return render(request, 'blog/blog-home.html', context)


def blog_single(request):
    # post = Post.objects.get(id=3)
    post = get_object_or_404(Post, pk=3, status=True)
    comments = Comment.objects.filter(
        post=post.id, approved=True).order_by('-created_at')
    context = {
        'title': 'Gamba',
        'content': 'lorem ipsum dolor sit amet, consectetur adip, lorem ipsum dolor, lorem ipsum dolor',
        'author': 'Asghar Farhadi',
        'post': post,
        'comments': comments,
    }
    if request.user.is_authenticated:
        # context += {
        #     'user': request.user
        # }
        context['user'] = request.user
    return render(request, 'blog/blog-single.html', context)


def test_view(request):
    # posts = Post.objects.all()
    posts = Post.objects.filter(status=1)
    context = {
        'title': 'Gamba',
        'subtitle': 'Ozaka',
        'content': 'lorem ipsum dolor sit amet, consectetur adip, lorem ipsum dolor, lorem ipsum dolor', 'author': 'ASghar Farhadi',
        'posts': posts
    }
    return render(request, 'test_view.html', context)


def name_tester(request, name):
    # posts = Post.objects.all()
    posts = Post.objects.filter(status=True)
    context = {
        'title': 'Gamba',
        'subtitle': 'Ozaka',
        'content': 'lorem ipsum dolor sit amet, consectetur adip, lorem ipsum dolor, lorem ipsum dolor',
        'author': 'Asghar Farhadi',
        'posts': posts,
        'name': name,
    }
    return render(request, 'test_view.html', context)


def name_family_tester(request, name, family):
    # posts = Post.objects.all()
    posts = Post.objects.filter(status=True)
    context = {
        'title': 'Gamba',
        'subtitle': 'Ozaka',
        'content': 'lorem ipsum dolor sit amet, consectetur adip, lorem ipsum dolor, lorem ipsum dolor',
        'author': 'Asghar Farhadi',
        'posts': posts,
        'name': name,
        'family': family
    }
    return render(request, 'test_view.html', context)


def name_family_age_tester(request, name, family, age):
    # posts = Post.objects.all()
    posts = Post.objects.filter(status=True)
    context = {
        'title': 'Gamba',
        'subtitle': 'Ozaka',
        'content': 'lorem ipsum dolor sit amet, consectetur adip, lorem ipsum dolor, lorem ipsum dolor',
        'author': 'Asghar Farhadi',
        'posts': posts,
        'name': name,
        'family': family,
        'age': age
    }
    return render(request, 'test_view.html', context)


def single_blog(request, pid):
    # posts = Post.objects.all()
    tags = Tag.objects.all()
    if request.method == 'POST':
        nxt = request.Post.get("next", None)
        # post = Post.objects.get(id=pid)
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            print("form.is_valid()")
            messages.success(
                request, 'Your Message has been sent successfully!')
        else:
            print("form.is_not_valid()")
            messages.warning(
                request, 'Your Message has not been sent successfully!')
        # print(f"comments.count() = {comments.count()}")
    else:
        form = CommentForm()
    post = get_object_or_404(Post, pk=pid, status=True)
    if post.login_require:
        return redirect("accounts:login_view")
    categories = Category.objects.all()
    comments = Comment.objects.filter(
        post=post.id, approved=True).order_by('-created_at')
    context = {
        'title': 'Gamba',
        'subtitle': 'Ozaka',
        'content': 'lorem ipsum dolor sit amet, consectetur adip, lorem ipsum dolor, lorem ipsum dolor',
        'author': 'Asghar Farhadi',
        # 'pid': pid,
        'post': post,
        # 'tags': tags,
        'categories': categories,
        'comments': comments,
        'form': form,
    }
    if request.user.is_authenticated:
        # context += {
        #     'user': request.user
        # }
        # print("request.user.username", request.user.username)
        context['user'] = request.user
    else:
        context['user'] = None
    return render(request, 'blog/blog-single.html', context)


def test_simple(request):
    # posts = Post.objects.all()
    posts = Post.objects.filter(status=1)
    context = {'title': 'Gamba',
               'subtitle': 'Ozaka',
               'content': 'lorem ipsum dolor sit amet, consectetur adip, lorem ipsum dolor, lorem ipsum dolor', 'author': 'ASghar Farhadi',
               'posts': posts}
    return render(request, 'test_simple.html', context)


def blog_search(request):
    # posts = get_list_or_404(Post, status=True)
    # pprint.pprint(request.__dict__)
    posts = Post.objects.filter(status=True)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(content__contains=s)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    context = {
        'posts': posts,
        'tags': tags,
        'categories': categories,
    }
    return render(request, 'blog/blog-home.html', context)


def post_comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your Message has been sent successfully!')
        else:
            messages.warning(
                request, 'Your Message has not been sent successfully!')
    else:
        form = CommentForm()
    context = {
        'form': form
    }
    return render(request, 'widgets/comment-post-widget.html', context)

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- start banner Area -->
  <section class="banner-area relative blog-home-banner" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
      <div class="row d-flex align-items-center justify-content-center">
        <div class="about-content blog-header-content col-lg-12">
          <h1 class="text-white">Dude You’re Getting a Telescope</h1>
          <p class="text-white">There is a moment in the life of any aspiring astronomer that it is time to buy that first</p>
          <a href="{% url 'blog:single' %}" class="primary-btn">View More</a>
        </div>
      </div>
    </div>
  </section>
  <!-- End banner Area -->

  <!-- Start top-category-widget Area -->
  {% include 'widgets/top-category-widget.html' %}
  <!-- End top-category-widget Area -->

  <!-- Start post-content Area -->
  <section class="post-content-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 posts-list">
          {% for post in posts %}
            <div class="single-post row">
              <div class="col-lg-3 col-md-3 meta-details">
                <ul class="tags">
                  {% for category in post.category.all %}
                    <li>
                      <a href="{% url 'blog:category_blog_view' category.name %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
                    </li>
                  {% endfor %}
                  {% comment %} {{ post.category.all|join:', ' }} {% endcomment %}
                </ul>
                <div class="user-details row">
                  <p class="user-name col-lg-12 col-md-12 col-6">
                    {% if post.author.get_full_name %}
                      <a href="{% url 'blog:author_blog_view' post.author.username %}">{{ post.author.get_full_name }}</a> <span class="lnr lnr-user"></span>
                    {% else %}
                      <a href="{% url 'blog:author_blog_view' post.author.username %}">{{ post.author.username }}</a> <span class="lnr lnr-user"></span>
                    {% endif %}
                  </p>
                  <p class="date col-lg-12 col-md-12 col-6">
                    <a href="#">{{ post.published_at|date:'d M Y' }}</a> <span class="lnr lnr-calendar-full"></span>
                  </p>
                  <p class="view col-lg-12 col-md-12 col-6">
                    <a href="#">{{ post.counted_view }} Views</a> <span class="lnr lnr-eye"></span>
                  </p>
                  <p class="comments col-lg-12 col-md-12 col-6">
                    <a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span>
                  </p>
                </div>
              </div>
              <div class="col-lg-9 col-md-9">
                <div class="feature-img">
                  <img class="img-fluid" src="{{ post.image.url }}" alt="" />
                </div>
                <a class="posts-title" href="{% url 'blog:single_blog' post.id %}"><h3>{{ post.title }}</h3></a>
                {% comment %} <p class="excert">{{ post.snippets }}</p> {% endcomment %}
                <p class="excert">{{ post.content|truncatechars:200 }}</p>
                {% comment %} <a href="blog-single.html" class="primary-btn">View More</a> {% endcomment %}
                <a href="{% url 'blog:single_blog' post.id %}" class="primary-btn">View More</a>
              </div>
            </div>
          {% endfor %}
          <nav class="blog-pagination justify-content-center d-flex">
            {% comment %} <ul class="pagination">
              <li class="page-item">
                <a href="#" class="page-link" aria-label="Previous"><span aria-hidden="true"><span class="lnr lnr-chevron-left"></span></span></a>
              </li>
            </ul> {% endcomment %}
            <ul class="pagination">
              {% if posts.has_previous %}
                <li class="page-item step-links">
                  <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                    {% comment %}previous{% endcomment %}
                    <span aria-hidden="true"><span class="lnr lnr-chevron-left"></span></span>
                  </a>
                </li>
                <li class="page-item step-links">
                  <a href="?page=1" class="page-link" aria-label="First">
                    {% comment %}&laquo; first{% endcomment %}
                    <span aria-hidden="true"><span class="lnr">First</span></span>
                  </a>
                </li>
              {% endif %}
              {% comment %} <li class="current page-item active">
                <a href="#" class="page-link">Page {{ posts.number }} of {{ posts.paginator.num_pages }}</a>
              </li> {% endcomment %}
              {% for page_number in posts.paginator.page_range %}
              <li class="page-item {% if page_number == posts.number %}current active{% endif %}">
                <a href="?page={{ page_number }}" class="page-link">Page {{ page_number }}</a>
              </li>
              {% endfor %}
              {% if posts.has_next %}
                <li class="current page-item">
                  <a href="?page={{ posts.paginator.num_pages }}" class="page-link" aria-label="Last">
                    {% comment %}&laquo; first{% endcomment %}
                    <span aria-hidden="true"><span class="lnr">Last</span></span>
                  </a>
                </li>
                <li class="current page-item">
                  <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                    {% comment %}next{% endcomment %}
                    <span aria-hidden="true"><span class="lnr lnr-chevron-right"></span></span>
                  </a>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
        {% include 'sidebar.html' %}
      </div>
    </div>
  </section>
  <!-- End post-content Area -->
{% endblock %}

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}
  <!-- start banner Area -->
  <section class="relative about-banner">
    <div class="overlay overlay-bg"></div>
    <div class="container">
      <div class="row d-flex align-items-center justify-content-center">
        <div class="about-content col-lg-12">
          {% if post.title %}
            <h1 class="text-white">{{ post.title }}</h1>
          {% else %}
            <h1 class="text-white">Title PlaceHolder</h1>
          {% endif %}
          <p class="text-white link-nav">
            <a href="{% url 'website:index' %}">Home</a>
            <span class="lnr lnr-arrow-right"></span>
            <a href="{% url 'blog:index' %}">Blog</a>
            <span class="lnr lnr-arrow-right"></span>
            <a href="{% url 'blog:single_blog' post.id %}">{{ post.title }}</a>
            {% if debug %}
              <span class="lnr lnr-arrow-right"></span>
              <a href="">Debug is Enabled</a>
            {% endif %}
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- End banner Area -->

  <!-- Start post-content Area -->
  <section class="post-content-area single-post-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 posts-list">
          <div class="single-post row">
            <div class="col-lg-12">
              <div class="feature-img">
                {% comment %} <img class="img-fluid" src="{% static 'img/blog/feature-img1.jpg' %}" alt="" /> {% endcomment %}
                <img class="img-fluid" src={{ post.image.url }} alt="" />
              </div>
            </div>
            <div class="col-lg-3 col-md-3 meta-details">
              <ul class="tags">
                {% for category in post.category.all %}
                <li>
                  <a href="#">{{ category.name}}</a>{% if not forloop.last %}, {% endif %}
                </li>
                {% endfor %}
              </ul>
              <div class="user-details row">
                {% if post %}
                  <p class="user-name col-lg-12 col-md-12 col-6">
                    {% if post.author.get_full_name %}
                      <a href="{% url 'blog:author_blog_view' post.author.username %}">{{ post.author.get_full_name }}</a> <span class="lnr lnr-user"></span>
                    {% else %}
                      <a href="{% url 'blog:author_blog_view' post.author.username %}">{{ post.author.username }}</a> <span class="lnr lnr-user"></span>
                    {% endif %}
                  </p>
                  <p class="date col-lg-12 col-md-12 col-6">
                    <a href="#">{{ post.created_at|date:"d M Y" }}</a> <span class="lnr lnr-calendar-full"></span>
                  </p>
                  <p class="view col-lg-12 col-md-12 col-6">
                    <a href="#">{{ post.counted_view }} Views</a> <span class="lnr lnr-eye"></span>
                  </p>
                  <p class="comments col-lg-12 col-md-12 col-6">
                    <a href="#">{{ comments|length }} Comment{% if comments|length > 1 %}s{% endif %}</a> <span class="lnr lnr-bubble"></span>
                  </p>
                  <ul class="social-links col-lg-12 col-md-12 col-6">
                    <li>
                      <a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-github"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-behance"></i></a>
                    </li>
                  </ul>
                {% else %}
                  <p class="user-name col-lg-12 col-md-12 col-6">
                    <a href="#">Mark wiens</a> <span class="lnr lnr-user"></span>
                  </p>
                  <p class="date col-lg-12 col-md-12 col-6">
                    <a href="#">12 Dec, 2017</a> <span class="lnr lnr-calendar-full"></span>
                  </p>
                  <p class="view col-lg-12 col-md-12 col-6">
                    <a href="#">1.2M Views</a> <span class="lnr lnr-eye"></span>
                  </p>
                  <p class="comments col-lg-12 col-md-12 col-6">
                    <a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span>
                  </p>
                  <ul class="social-links col-lg-12 col-md-12 col-6">
                    <li>
                      <a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-github"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-behance"></i></a>
                    </li>
                  </ul>
                {% endif %}
              </div>
            </div>
            <div class="col-lg-9 col-md-9">
              {% if post %}
                <h1>{{ post.title }}</h1>
                {% comment %} <p>{{ post.content }}</p> {% endcomment %}
                <p>{{ post.content|truncatechars:200 }}</p>
              {% else %}
                {% if title %}
                  <h1>{{ title }}</h1>
                {% else %}
                  <h3 class="mt-20 mb-20">Astronomy Binoculars A Great Alternative</h3>
                {% endif %}
                {% if post.content %}
                  <p class="excert">{{ post.content }}</p>
                {% else %}
                  <p class="excert">MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction.</p>
                  <p>Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed</p>
                  <p>Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed</p>
                {% endif %}
              {% endif %}
            </div>
            <div class="col-lg-12">
              {% if post %}
              <div class="quotes">{{ post.content|safe}}</div>
              {% else %}
              <div class="quotes">MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training.</div>
              {% endif %}
              <div class="row mt-30 mb-30">
                <div class="col-6">
                  {% comment %} <img class="img-fluid" src="{% static 'img/blog/post-img1.jpg' %}" alt="" /> {% endcomment %}
                  <img class="img-fluid" src="{{ post.image.url }}" alt="" />
                </div>
                <div class="col-6">
                  {% comment %} <img class="img-fluid" src="{% static 'img/blog/post-img2.jpg' %}" alt="" /> {% endcomment %}
                  <img class="img-fluid" src="{{ post.image.url }}" alt="" />
                </div>
                {% comment %} <div class="col-lg-12 mt-30">
                  <p>MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower.</p>
                  <p>MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower.</p>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
          {% include 'widgets/navigation-area-widget.html' %}
          {% include 'widgets/comment-widget.html' %}
          {% include 'widgets/comment-post-widget.html' %}
          {% comment %} {% include 'widgets/disqus-comment-widget.html' %} {% endcomment %}
        </div>
        {% include 'sidebar.html' %}
      </div>
    </div>
  </section>
  <!-- End post-content Area -->
{% endblock %}