accounts/urls.py
from . import views
from django.urls import path
from blog.models import Post


app_name = 'accounts'
urlpatterns = [
    path("", views.index, name="index"),
    # login
    path("login/", views.login_view, name="login_view"),
    # logout
    path("logout/", views.logout_view, name="logout_view"),
    # registration/signup
    path("signup/", views.signup_view, name="signup_view"),
]

blog/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import path, include
from blog import views
from .feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path("", views.blog_view, name="index"),
    path("category/<str:category_name>", views.blog_view, name="category_blog_view"),
    path("tag/<str:tag_name>", views.blog_view, name="tag_blog_view"),
    path("rss/feed/", LatestEntriesFeed(), name="LatestEntriesFeed"),
    path("author/<str:author_name>", views.blog_view, name="author_blog_view"),
    path("search/", views.blog_search, name="blog_search"),
    path("<int:pid>", views.single_blog, name="single_blog"),
    path("comment", views.post_comment, name="post_comment"),
    path("single", views.blog_single, name="single"),
    path("test_view", views.test_view, name="test_view"),
    path("test_simple", views.test_simple, name="test_simple"),
    path("<str:name>", views.name_tester, name="name_tester"),
    path("<str:name>/<str:family>", views.name_family_tester, name="name_family_tester"),
    path("<str:name>/<str:family>/<int:age>", views.name_family_age_tester, name="name_family_age_tester"),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website import views
from website.sitemaps import WebsiteStaticViewSitemap

sitemaps = {
    'websitestatic': WebsiteStaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("http-test/", views.http_test, name="http-test"),
    # path("json-test/", views.json_test, name="json-test"),
    path("", include("website.urls"), name="website"),
    # path("website/", include("website.urls"), name="website"),
    path("blog/", include("blog.urls"), name="blog"),
    # path("accounts/", include("accounts.urls"), name="accounts"),
    path("accounts/", include("django.contrib.auth.urls"), name="accounts"),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", include("robots.urls"), name="robots"),
    path("__debug__/", include("debug_toolbar.urls")),
]

# static ('static, 'base / static')
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
import django.contrib.auth.urls

from website import views
app_name = 'website'
urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.index, name="home"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("newsletter", views.newsletter, name="newsletter"),
    path("test_view", views.test_view, name="test_view"),
    path("test", views.test, name="test"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
  <head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Favicon -->
    {% comment %} <link rel="shortcut icon" href="img/fav.png" /> {% endcomment %}
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}" />
    <!-- Author Meta -->
    <meta name="author" content="colorlib" />
    <!-- Meta Description -->
    <meta name="description" content="" />
    <!-- Meta Keyword -->
    <meta name="keywords" content="" />
    <!-- meta character set -->
    <meta charset="UTF-8" />
    <!-- Site Title -->
    <title>Travel</title>

    {% comment %} <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet" /> {% endcomment %}
    <!-- 
			CSS
			=============================================  -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
  </head>
  <body>
    <header id="header">
      <div class="header-top">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6 col-sm-6 col-6 header-top-left">
              <ul>
                {% if request.user.is_authenticated %}
                <li>
                  <a href="#">{{request.user.username}}</a>
                </li>
                <li>
                  {% comment %} <a href="{% url 'accounts:logout_view' %}">Logout</a> {% endcomment %}
                  <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                  {% comment %} <a href="{% url 'accounts:login_view' %}">Login</a> {% endcomment %}
                  <a href="{% url 'login' %}">Login</a>
                </li>
                <li>
                  {% comment %} <a href="{% url 'accounts:signup_view' %}">SignUP</a> {% endcomment %}
                  {% comment %} <a href="{% url 'register' %}">SignUP</a> {% endcomment %}
                </li>
                {% endif %}
                {% comment %} <li>
                  <a href="#">Visit Us</a>
                </li>
                <li>
                  <a href="#">Buy Tickets</a>
                </li> {% endcomment %}
              </ul>
            </div>
            <div class="col-lg-6 col-sm-6 col-6 header-top-right">
              <div class="header-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
          <div id="logo">
            <a href="{% url 'website:index' %}">
              {% comment %} <img src={% static "img/logo.png"%} alt="" title="" /> {% endcomment %}
              <img src={% static "img/logo.png"%} alt="" title="" />
            </a>
          </div>
          <nav id="nav-menu-container">
            <ul class="nav-menu">
              <li>
                <a href="{% url 'website:index' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'website:about' %}">About</a>
              </li>

              <li class="menu-has-children">
                {% if debug %}
                <a href="">Blog</a>
                <ul>
                  <li>
                    <a href="{% url 'blog:index' %}">Blog Home</a>
                  </li>
                  {% comment %} <li>
                    <a href="{% url 'blog:single' %}">Blog Single</a>
                  </li> {% endcomment %}
                  <li>
                    <a href="{% url 'blog:test_view' %}">Test View</a>
                  </li>
                </ul>
                {% else %}
                <a href="{% url 'blog:index' %}">Blog</a>
                {% endif %}
              </li>
              {% comment %} <li class="menu-has-children">
                <a href="">Pages</a>
                <ul>
                  <li>
                    <a href="elements.html">Elements</a>
                  </li>
                  <li class="menu-has-children">
                    <a href="">Level 2</a>
                    <ul>
                      <li>
                        <a href="#">Item One</a>
                      </li>
                      <li>
                        <a href="#">Item Two</a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li> {% endcomment %}
              <li class="menu-has-children">
                {% if request.user.is_authenticated %}
                {% comment %} <a href="{% url 'accounts:index' %}">My Account</a> {% endcomment %}
                <a href="">My Account</a>
                <ul>
                  <li>
                    {% comment %} <a href="{% url 'accounts:logout_view' %}">Logout</a> {% endcomment %}
                    <a href="{% url 'logout' %}">Logout</a>
                  </li>
                </ul>
                {% else %}
                {% comment %} <a href="{% url 'accounts:index' %}">My Account</a> {% endcomment %}
                <a href="">My Account</a>
                <ul>
                  <li>
                    {% comment %} <a href="{% url 'accounts:login_view' %}">Login</a> {% endcomment %}
                    <a href="{% url 'login' %}">Login</a>
                  </li>
                  <li class="menu-has-children">
                    {% comment %} <a href="{% url 'accounts:signup_view' %}">Sign UP</a> {% endcomment %}
                    <a href="">Sign UP</a>
                  </li>
                </ul>
                {% endif %}
              </li>
              <li>
                <a href="{% url 'website:contact' %}">Contact</a>
              </li>
            </ul>
          </nav>
          <!-- #nav-menu-container -->
        </div>
      </div>
    </header>
    <!-- #header -->

{% block content %}
{% endblock content %}

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Agency</h6>
              <p>The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Navigation Links</h6>
              <div class="row">
                <div class="col">
                  <ul>
                    <li>
                      <a href="#">Home</a>
                    </li>
                    <li>
                      <a href="#">Feature</a>
                    </li>
                    <li>
                      <a href="#">Services</a>
                    </li>
                    <li>
                      <a href="#">Portfolio</a>
                    </li>
                  </ul>
                </div>
                <div class="col">
                  <ul>
                    <li>
                      <a href="#">Team</a>
                    </li>
                    <li>
                      <a href="#">Pricing</a>
                    </li>
                    <li>
                      <a href="#">Blog</a>
                    </li>
                    <li>
                      <a href="#">Contact</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Newsletter</h6>
              <p>For business professionals caught between high OEM price and mediocre print and graphic output.</p>
              <div>
                <form action="{% url 'website:newsletter' %}" method="post" class="subscription relative">
                  {% csrf_token %}
                  <div class="input-group d-flex flex-row">
                    <input name="email" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email" />
                    <button class="btn bb-btn" type="submit"><span class="lnr lnr-location"></span></button>
                  </div>
                  <div class="mt-10 info"></div>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget mail-chimp">
              <h6 class="mb-20">InstaFeed</h6>
              <ul class="instafeed d-flex flex-wrap">
                <li>
                  <img src={% static "img/i1.jpg"%} alt="" />
                </li>
                <li>
                  <img src={% static "img/i2.jpg"%} alt="" />
                </li>
                <li>
                  <img src={% static "img/i3.jpg"%} alt="" />
                </li>
                <li>
                  <img src={% static "img/i4.jpg"%} alt="" />
                </li>
                <li>
                  <img src={% static "img/i5.jpg"%} alt="" />
                </li>
                <li>
                  <img src={% static "img/i6.jpg"%} alt="" />
                </li>
                <li>
                  <img src={% static "img/i7.jpg"%} alt="" />
                </li>
                <li>
                  <img src={% static "img/i8.jpg"%} alt="" />
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="row footer-bottom d-flex justify-content-between align-items-center">
          <p class="col-lg-8 col-sm-12 footer-text m-0">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>
                              document.write(new Date().getFullYear())
                            {% comment %} </script>All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> {% endcomment %}
                            </script>
                            All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
          <div class="col-lg-4 col-sm-12 footer-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->

    {% comment %} <script src={% static 'js/vendor/jquery-2.2.4.min.js'%}></script> {% endcomment %}
    <script src={% static 'js/vendor/jquery-2.2.4.min.js'%}></script>
    <script src={% static 'js/popper.min.js'%}></script>
    <script src={% static 'js/vendor/bootstrap.min.js'%}></script>
    {% comment %} <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script> {% endcomment %}
    <script src={% static 'js/jquery-ui.js'%}></script>
    <script src={% static 'js/easing.min.js'%}></script>
    <script src={% static 'js/hoverIntent.js'%}></script>
    <script src={% static 'js/superfish.min.js'%}></script>
    <script src={% static 'js/jquery.ajaxchimp.min.js'%}></script>
    <script src={% static 'js/jquery.magnific-popup.min.js'%}></script>
    <script src={% static 'js/jquery.nice-select.min.js'%}></script>
    <script src={% static 'js/owl.carousel.min.js'%}></script>
    {% comment %} <script src={% static 'js/mail-script.js'%}></script> {% endcomment %}
    <script src={% static 'js/main.js'%}></script>
  </body>
</script>
</html>

templates/popular_posts.html
{% load blog_tags %}
<ul>
  {% for post in posts %}
    <li>{{ post.title }}</li>
    <li>{{ post.content|snippetarg:50 }}</li>
  {% endfor %}
</ul>

templates/test_simple.html
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test_simple</title>
</head>
<body>
    <h1>test_simple Header</h1>
    <p>test: {% hello %} </p>
    <p>test: {% plustwo 2 %} </p>
    <p>test: {% plustwo %} </p>
    <p>test: {% totalposts %} </p>
    <p>test: {% posts %} </p>
    {% for post in posts%}
    <p>title: {{ post.title }}</p>
    <p>snippet: {{ post.content|snippetarg:10 }} </p>
    {% endfor %}

    {% popularposts 4 %}
</body>
</html>

templates/test_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- start banner Area -->
  <section class="about-banner relative">
    <div class="overlay overlay-bg"></div>
    <div class="container">
      <div class="row d-flex align-items-center justify-content-center">
        <div class="about-content col-lg-12">
          {% if title %}
            <h1 class="text-white">{{ title }}</h1>
          {% else %}
            <h1 class="text-white">test_view</h1>
          {% endif %}
          <p class="text-white link-nav">
            <a href="{% url 'website:index' %}">Home</a>
            <span class="lnr lnr-arrow-right"></span>
            <a href="{% url 'website:about' %}">About Us</a>
          </p>
          {% if name %}
            <p class="text-white link-nav">
              <a href="{% url 'website:index' %}">Name = {{ name }}</a>
              <span class="lnr lnr-arrow-right"></span>
              {% if family %}
                <a href="{% url 'website:index' %}">Family = {{ family }}</a>
                <span class="lnr lnr-arrow-right"></span>
                {% if age %}
                  <a href="{% url 'website:index' %}">Age = {{ age }}</a>
                  <span class="lnr lnr-arrow-right"></span>
                {% endif %}
              {% endif %}
            </p>
          {% endif %}
          {% if post %}
          <p>
            <a href="{% url 'website:index' %}">Post Title = {{ post.title }}</a>
                  <span class="lnr lnr-arrow-right"></span>
          </p>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  <!-- End banner Area -->
  <!-- Start about-info Area -->
  <section class="about-info-area section-gap">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 info-left">
          <img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="" />
        </div>
        <div class="col-lg-6 info-right">
          {% if subtitle %}
            <h6>{{ subtitle }}</h6>
          {% else %}
            <h6>test_view</h6>
          {% endif %}
          {% if title %}
            <h1>{{ title }}</h1>
          {% else %}
            <h1>test_view</h1>
          {% endif %}
          {% if content %}
            <p>{{ content }}</p>
          {% else %}
            <p>Here, I focus on a range of items and features that we use in life without giving them a second thought. such as Coca Cola. Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  <!-- End about-info Area -->

  <!-- Start post-content Area -->
  <section class="post-content-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 posts-list">
          {% for post in posts %}
            <div class="single-post row">
              <div class="col-lg-3 col-md-3 meta-details">
                <ul class="tags">
                  <li>
                    <a href="#">Food,</a>
                  </li>
                  <li>
                    <a href="#">Technology,</a>
                  </li>
                  <li>
                    <a href="#">Politics,</a>
                  </li>
                  <li>
                    <a href="#">Lifestyle</a>
                  </li>
                </ul>
                <div class="user-details row">
                  <p class="user-name col-lg-12 col-md-12 col-6">
                    <a href="#">Mark wiens</a> <span class="lnr lnr-user"></span>
                  </p>
                  <p class="date col-lg-12 col-md-12 col-6">
                    <a href="#">{{ post.created_at }}</a> <span class="lnr lnr-calendar-full"></span>
                  </p>
                  <p class="view col-lg-12 col-md-12 col-6">
                    <a href="#">{{ post.counted_view }} Views</a> <span class="lnr lnr-eye"></span>
                  </p>
                  <p class="comments col-lg-12 col-md-12 col-6">
                    <a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span>
                  </p>
                </div>
              </div>
              <div class="col-lg-9 col-md-9">
                <div class="feature-img">
                  <img class="img-fluid" src="{% static 'img/blog/feature-img1.jpg' %}" alt="" />
                </div>
                {% if post.title %}
                  <a class="posts-title" href="blog-single.html"><h3>{{ post.title }}</h3></a>
                {% else %}
                  <a class="posts-title" href="blog-single.html"><h3>Post.title PlaceHolder</h3></a>
                {% endif %}
                {% if post.content %}
                  <p class="excert">{{ post.content }}</p>
                {% else %}
                  <p class="excert">Post.content PlaceHolder</p>
                {% endif %}
                <a href="blog-single.html" class="primary-btn">View More</a>
              </div>
            </div>
          {% endfor %}
          <nav class="blog-pagination justify-content-center d-flex">
            <ul class="pagination">
              <li class="page-item">
                <a href="#" class="page-link" aria-label="Previous"><span aria-hidden="true"><span class="lnr lnr-chevron-left"></span></span></a>
              </li>
              <li class="page-item">
                <a href="#" class="page-link">01</a>
              </li>
              <li class="page-item active">
                <a href="#" class="page-link">02</a>
              </li>
              <li class="page-item">
                <a href="#" class="page-link">03</a>
              </li>
              <li class="page-item">
                <a href="#" class="page-link">04</a>
              </li>
              <li class="page-item">
                <a href="#" class="page-link">09</a>
              </li>
              <li class="page-item">
                <a href="#" class="page-link" aria-label="Next"><span aria-hidden="true"><span class="lnr lnr-chevron-right"></span></span></a>
              </li>
            </ul>
          </nav>
        </div>
        <div class="col-lg-4 sidebar-widgets">
          <div class="widget-wrap">
            <div class="single-sidebar-widget search-widget">
              <form class="search-form" action="#">
                <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" />
                <button type="submit"><i class="fa fa-search"></i></button>
              </form>
            </div>
            <div class="single-sidebar-widget user-info-widget">
              <img src="{% static 'img/blog/user-info.png' %}" alt="" />
              <a href="#"><h4>Charlie Barber</h4></a>
              <p>Senior blog writer</p>
              <ul class="social-links">
                <li>
                  <a href="#"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-github"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-behance"></i></a>
                </li>
              </ul>
              <p>Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.</p>
            </div>
            <div class="single-sidebar-widget popular-post-widget">
              <h4 class="popular-title">Popular Posts</h4>
              <div class="popular-post-list">
                <div class="single-post-list d-flex flex-row align-items-center">
                  <div class="thumb">
                    <img class="img-fluid" src="{% static 'img/blog/pp1.jpg' %}" alt="" />
                  </div>
                  <div class="details">
                    <a href="blog-single.html"><h6>Space The Final Frontier</h6></a>
                    <p>02 Hours ago</p>
                  </div>
                </div>
                <div class="single-post-list d-flex flex-row align-items-center">
                  <div class="thumb">
                    <img class="img-fluid" src="{% static 'img/blog/pp2.jpg' %}" alt="" />
                  </div>
                  <div class="details">
                    <a href="blog-single.html"><h6>The Amazing Hubble</h6></a>
                    <p>02 Hours ago</p>
                  </div>
                </div>
                <div class="single-post-list d-flex flex-row align-items-center">
                  <div class="thumb">
                    <img class="img-fluid" src="{% static 'img/blog/pp3.jpg' %}" alt="" />
                  </div>
                  <div class="details">
                    <a href="blog-single.html"><h6>Astronomy Or Astrology</h6></a>
                    <p>02 Hours ago</p>
                  </div>
                </div>
                <div class="single-post-list d-flex flex-row align-items-center">
                  <div class="thumb">
                    <img class="img-fluid" src="{% static 'img/blog/pp4.jpg' %}" alt="" />
                  </div>
                  <div class="details">
                    <a href="blog-single.html"><h6>Asteroids telescope</h6></a>
                    <p>02 Hours ago</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="single-sidebar-widget ads-widget">
              <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt="" /></a>
            </div>
            <div class="single-sidebar-widget post-category-widget">
              <h4 class="category-title">Post Catgories</h4>
              <ul class="cat-list">
                <li>
                  <a href="#" class="d-flex justify-content-between">
                    <p>Technology</p>
                    <p>37</p>
                  </a>
                </li>
                <li>
                  <a href="#" class="d-flex justify-content-between">
                    <p>Lifestyle</p>
                    <p>24</p>
                  </a>
                </li>
                <li>
                  <a href="#" class="d-flex justify-content-between">
                    <p>Fashion</p>
                    <p>59</p>
                  </a>
                </li>
                <li>
                  <a href="#" class="d-flex justify-content-between">
                    <p>Art</p>
                    <p>29</p>
                  </a>
                </li>
                <li>
                  <a href="#" class="d-flex justify-content-between">
                    <p>Food</p>
                    <p>15</p>
                  </a>
                </li>
                <li>
                  <a href="#" class="d-flex justify-content-between">
                    <p>Architecture</p>
                    <p>09</p>
                  </a>
                </li>
                <li>
                  <a href="#" class="d-flex justify-content-between">
                    <p>Adventure</p>
                    <p>44</p>
                  </a>
                </li>
              </ul>
            </div>
            <div class="single-sidebar-widget newsletter-widget">
              <h4 class="newsletter-title">Newsletter</h4>
              <p>Here, I focus on a range of items and features that we use in life without giving them a second thought.</p>
              <div class="form-group d-flex flex-row">
                <div class="col-autos">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                      </div>
                    </div>
                    <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" />
                  </div>
                </div>
                <a href="#" class="bbtns">Subcribe</a>
              </div>
              <p class="text-bottom">You can unsubscribe at any time</p>
            </div>
            <div class="single-sidebar-widget tag-cloud-widget">
              <h4 class="tagcloud-title">Tag Clouds</h4>
              <ul>
                <li>
                  <a href="#">Technology</a>
                </li>
                <li>
                  <a href="#">Fashion</a>
                </li>
                <li>
                  <a href="#">Architecture</a>
                </li>
                <li>
                  <a href="#">Fashion</a>
                </li>
                <li>
                  <a href="#">Food</a>
                </li>
                <li>
                  <a href="#">Technology</a>
                </li>
                <li>
                  <a href="#">Lifestyle</a>
                </li>
                <li>
                  <a href="#">Art</a>
                </li>
                <li>
                  <a href="#">Adventure</a>
                </li>
                <li>
                  <a href="#">Food</a>
                </li>
                <li>
                  <a href="#">Lifestyle</a>
                </li>
                <li>
                  <a href="#">Adventure</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End post-content Area -->
{% endblock %}